### ISSUE TITLE
Xcode 13 support

### ISSUE THREAD

**Issue by bartzet** [theappbusiness/TABTestKit#156]
👋 

We are getting errors after we migrated to Xcode 13. All the tests are running just fine on Xcode 12.5

![image](https://user-images.githubusercontent.com/23279455/137352821-634d1417-3082-4bb4-86d9-b927f7c4edd5.png)
![image](https://user-images.githubusercontent.com/23279455/137352906-8dd85687-e136-4b75-8f21-cc0ec987a662.png)

Could you please make the TABTestKit compatible with Xcode 13?

**Comment by theblixguy** [comment]
It's already compatible as of 1.8.0. You just need to use `waitFor` instead of `await` here. In many cases you'll get an error advising you to change the name, but in some cases the compiler doesn't give the unavailability annotations a chance to fire and just infers it as a keyword instead of the `await` function.
